### ISSUE TITLE
Can't Recompile Lazarus after installation

### ISSUE THREAD

**Issue by JoeJoeTV** [LongDirtyAnimAlf/fpcupdeluxe#201]
When installing Lazarus and FPC (both stable), I can't recompile Lazarus from within the IDE (fresh install).
I get the error: 
`Warning: Recompiling clocale, checksum changed for System`
`lazarus.pp(54,3) Fatal: Cannot find clocale used by Lazarus. Make sure all ppu files of a package are in its output directory. ppu in wrong directory=/opt/fpcupdeluxe/fpc/units/x86_64-linux/rtl-extra/clocale.ppu..`

I also looked in the FPC output from Lazarus and found clocale.ppu.

Extra Info: It worked before I reinstalled fpcupdeluxe (deleted everything in folder) and I have installed lamw_manager since then (if that helps).

OS: Linux Mint 19.3 Cinnamon
Lazarus 2.0.6 (stable)
FPC 3.0.4 (stable)
x86_64

**Comment by LongDirtyAnimAlf** [comment]
I will look into it.

**Comment by JoeJoeTV** [comment]
I found this error message during the installation of Lazarus stable + FPC stable, maybe it helps:

```Executing: patch -p0 -N --no-backup-if-mismatch -i /opt/fpcupdeluxe/tmp/fpcup00000/fpcpatch_all_makesearchpath_stable_3_0_4.patch (working dir: /opt/fpcupdeluxe/fpcsrc)
patching file Makefile
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file Makefile.rej
fpcupdeluxe: ERROR: FPCNativeInstaller (GetModule: FPC): FPC patching with /opt/fpcupdeluxe/patchfpc/fpcpatch_all_makesearchpath_stable_3_0_4.patch failed.

fpcupdeluxe: ERROR: FPCNativeInstaller (GetModule: FPC): FPC patch output: patching file Makefile
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file Makefile.rej

fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): Trying to patch FPC with /opt/fpcupdeluxe/patchfpc/fpcpatch_linux_linker_stable_3_0_4.patch
Executing: patch -p0 -N --no-backup-if-mismatch -i /opt/fpcupdeluxe/tmp/fpcup00000/fpcpatch_linux_linker_stable_3_0_4.patch (working dir: /opt/fpcupdeluxe/fpcsrc)
patching file compiler/systems/t_linux.pas
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file compiler/systems/t_linux.pas.rej
fpcupdeluxe: ERROR: FPCNativeInstaller (GetModule: FPC): FPC patching with /opt/fpcupdeluxe/patchfpc/fpcpatch_linux_linker_stable_3_0_4.patch failed.

fpcupdeluxe: ERROR: FPCNativeInstaller (GetModule: FPC): FPC patch output: patching file compiler/systems/t_linux.pas
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file compiler/systems/t_linux.pas.rej
```

**Comment by LongDirtyAnimAlf** [comment]
Would you mind trying the latest release ?

**Comment by JoeJoeTV** [comment]
I tried it with fpcupdeluxe 1.6.8k, but sill no luck, same error.
I noticed, that when I remove all the files in the fpcupdeluxe directory except the executeable and the fpcupdeluxe.ini file, so I can reinstall fpc and lazarus, I get an error when I want to install fpc and lazarus stable:
![image](https://user-images.githubusercontent.com/34209417/78128491-5311cf00-7416-11ea-9bc8-2f26a4c05940.png)

**Comment by LongDirtyAnimAlf** [comment]
Dreadful error. Hunting it for a very long time now.
Not able to find the cause.
Not able to find a remedy.
Sorry about this.

**Comment by JoeJoeTV** [comment]
I saw, but I don't think that's the cause for Lazarus not compiling, or is it?
Because if I update it after the first attempt, it installs just fine.
Maybe it has something to do with the fpcupdeluxe.ini file that I **__didn't__** delete because of the installation dir.

**Comment by LongDirtyAnimAlf** [comment]
You are very welcome to help eliminate this error, so please feel free to try to reproduce it.
If you are able to reproduce, please tell me how, and I will start the hunt !!

**Comment by JoeJoeTV** [comment]
Are there any updates on this, because normally I use fpcupdeluxe as my main Lazarus install, and I don't want to install yet another instance

**Comment by JoeJoeTV** [comment]
> You are very welcome to help eliminate this error, so please feel free to try to reproduce it.
> If you are able to reproduce, please tell me how, and I will start the hunt !!

On this, I'm not sure, but it may have something to do with [LAMW4Linux-Installer](https://github.com/DanielOliveiraSouza/LAMW4Linux-installer), because before installing that it worked, but I also updated fpcupdeluxe, but I'm not sure what version I had before. I don't want to remove and reinstall LAMW4Linux, because I use it and it's a long process.

**Comment by LongDirtyAnimAlf** [comment]
Most likely, this issue was caused by a long standing bug in Lazarus.
https://bugs.freepascal.org/view.php?id=36318
This has been solved.
So closing.

**Comment by JoeJoeTV** [comment]
This issue still exists in the newest version of fpcupdeluxe with Lazarus 2.2.0 and fpc 3.2.2 (so stable & stable).
I mentioned that i had LAMW4Linux installed. I also have it installed now, but I don't know why it should affect fpcupdeluxe.

It's still the same "can't find clocale" error as before.

My Specs are:
OS: Linux Mint 20.3 Cinnamon 64bit
Lazarus 2.2.0
FPC 3.2.2
fpcupdeluxe 2.2.0h

**Comment by LongDirtyAnimAlf** [comment]
Yes, this error is due to another install unfortunately. And this install has, most likely, added some paths into the environment.
https://forum.lazarus.freepascal.org/index.php?topic=51837.0
Please check if removing this install or changing the env path solves this.

**Comment by JoeJoeTV** [comment]
This is my `PATH` environment variable. Is there a way tro gewt them to work together?
```PATH=/home/joejoetv/spicetify-cli:/home/joejoetv/.opam/4.12.0/bin:/home/joejoetv/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/media/data/Programme/LAMW4Linux/ndk-toolchain:/media/data/Programme/LAMW4Linux/gradle-6.6.1/bin```

**Comment by LongDirtyAnimAlf** [comment]
Well. Your path should not be a problem.
Can you do a system wide search for clocale.pp and clocale.ppu ?

**Comment by JoeJoeTV** [comment]
Ok, did a system wide search. Since I installed Lazarus from the normal deb Packges from lazarus-ide.org, aswell as LAMW4Linx and now fpcupdeluxe(I just wanted to use that for cross compiling), have three directories(well 2 for LAMW4Linux):
![image](https://user-images.githubusercontent.com/34209417/150980743-dcbcb172-bf98-43dc-930a-bc0c88c1dfa1.png)

And the ppu:
![image](https://user-images.githubusercontent.com/34209417/150980793-972ef2b3-07ee-421d-a54b-c3eefde95c6b.png)

**Comment by LongDirtyAnimAlf** [comment]
Please try the following:
Rename /usr/lib/fpc/3.2.2/..... to something like /usr/lib/fpc/3.2.2.2.2.2/.... (to prevent it from being found)
And re-run fpcupdeluxe again. As a test.

**Comment by JoeJoeTV** [comment]
> Please try the following: Rename /usr/lib/fpc/3.2.2/..... to something like /usr/lib/fpc/3.2.2.2.2.2/.... (to prevent it from being found) And re-run fpcupdeluxe again. As a test.

I did that and it worked!
So the Lazarus that is built by fpcupdeluxe is using the system fp compiler instead of the one built by fpcupdeluxe, I presume?

**Comment by LongDirtyAnimAlf** [comment]
That might be the case, but that should not cause this issue.
There are two possible causes:
* fpcupdeluxe bugger
* Lazarus Makefile bugger
I will look into this and try to reproduce.
